### ISSUE TITLE
Use "import type"

### ISSUE THREAD

**Issue by philippviereck** [supabase/realtime-js#229]
# Bug report

## Describe the bug

Typescript errors when using realtime-js in SvelteKit.

`npm run check:`
```
/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/lib/push.ts:2:1
Error: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
import { DEFAULT_TIMEOUT } from '../lib/constants'
import RealtimeChannel from '../RealtimeChannel'



/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeClient.ts:173:3
Hint: This may be converted to an async function.
   */
  removeChannel(
    channel: RealtimeChannel


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeClient.ts:187:3
Hint: This may be converted to an async function.
   */
  removeAllChannels(): Promise<RealtimeRemoveChannelResponse[]> {
    return Promise.all(


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeClient.ts:1:30
Error: Could not find a declaration file for module 'websocket'. '/Users/********/supabase-realtime-js-typescript-errors/node_modules/websocket/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/websocket` if it exists or add a new declaration (.d.ts) file containing `declare module 'websocket';`
import { w3cwebsocket } from 'websocket'
import {


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeClient.ts:14:27
Error: 'RealtimeChannelOptions' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
import Serializer from './lib/serializer'
import RealtimeChannel, { RealtimeChannelOptions } from './RealtimeChannel'



/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts:6:1
Error: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

import {
  PresenceOpts,
  PresenceOnJoinCallback,
  PresenceOnLeaveCallback,
} from 'phoenix'
import RealtimeChannel from './RealtimeChannel'


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts:7:3
Error: 'PresenceOpts' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
import {
  PresenceOpts,
  PresenceOnJoinCallback,


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts:8:3
Error: 'PresenceOnJoinCallback' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
  PresenceOpts,
  PresenceOnJoinCallback,
  PresenceOnLeaveCallback,


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts:9:3
Error: 'PresenceOnLeaveCallback' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
  PresenceOnJoinCallback,
  PresenceOnLeaveCallback,
} from 'phoenix'


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts:11:1
Error: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
} from 'phoenix'
import RealtimeChannel from './RealtimeChannel'



/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/lib/transformers.ts:109:20
Hint: JSDoc '@param' tag has name 'stringValue', but there is no parameter with that name.
 * @param {String} type A postgres column type
 * @param {String} stringValue The cell value
 *


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeChannel.ts:3:1
Error: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
import Push from './lib/push'
import RealtimeClient from './RealtimeClient'
import Timer from './lib/timer'


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeChannel.ts:6:3
Error: 'RealtimePresenceJoinPayload' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
import RealtimePresence, {
  RealtimePresenceJoinPayload,
  RealtimePresenceLeavePayload,


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeChannel.ts:7:3
Error: 'RealtimePresenceLeavePayload' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
  RealtimePresenceJoinPayload,
  RealtimePresenceLeavePayload,
  RealtimePresenceState,


/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimeChannel.ts:8:3
Error: 'RealtimePresenceState' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
  RealtimePresenceLeavePayload,
  RealtimePresenceState,
  REALTIME_PRESENCE_LISTEN_EVENTS,

```

`npm run dev` and visiting route that uses realtime-js
```
Cannot find module 'phoenix' imported from '/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts'
Error: Cannot find module 'phoenix' imported from '/Users/********/supabase-realtime-js-typescript-errors/node_modules/@supabase/realtime-js/src/RealtimePresence.ts'
    at viteResolve (file:///Users/********/supabase-realtime-js-typescript-errors/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:53469:25)
    at nodeImport (file:///Users/********/supabase-realtime-js-typescript-errors/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:53504:15)
    at ssrImport (file:///Users/********/supabase-realtime-js-typescript-errors/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:53399:20)
    at eval (/node_modules/@supabase/realtime-js/src/RealtimePresence.ts:3:50)
    at instantiateModule (file:///Users/********/supabase-realtime-js-typescript-errors/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:53445:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git clone https://github.com/philippviereck/supabase-realtime-js-typescript-errors.git`
2. `cd supabase-realtime-js-typescript-errors`
3. `npm i && npm run check` (see errors related to realtime-js)
4. create .env
5. `npm run dev`
6. go to `localhost:{port}/BUG` (Actual runtime error due to not using type import)

## Expected behavior

No errors.

## Screenshots

-
## System information

- OS: macOS
- Browser all
- Versions:
Example uses:
```
 "@supabase/auth-helpers-sveltekit": "^0.8.3",
"@supabase/supabase-js": "^2.0.4",
```
But it's the same for:
```
"@supabase/auth-helpers-sveltekit": "^0.9.0",
"@supabase/supabase-js": "^2.11.0",
```
- Version of Node.js: v18.14.0

**Comment by philippviereck** [comment]
Also, this happens on the server. When setting `ssr=false` in `/BUG/+page.ts` (from the example repo), then there is a different error which I don't quite understand why. 
![image](https://user-images.githubusercontent.com/105976309/226195469-965e9999-30e3-41c4-ae6e-8f125b78567b.png)
